[general]
live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "ArrowUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "ArrowDown"
mods = "Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 100
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

