" ------------------------ "
" VIM CONFIG
" Pedro P. Bittencourt
" github.com/pbittencourt
" ------------------------ "

set nocompatible
filetype off

" ------------------------------------------------------------------ "
" VUNDLE SECTION BEGIN

" Check OS
if has('win32')
    " convert / to \
    set shellslash 

    " Set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin('~/vimfiles/bundle')

    " Let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'

    " colorscheme
    set background=light
    colorscheme gruvbox
else
    " Set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()

    " Let Vundle manage Vundle, required
    Plugin 'gmarik/Vundle.vim'

    " Spell checking for markdown and tex documents
    " (it's not working on windows)
    autocmd BufRead,BufNewFile *.md setlocal spell spelllang=pt
    autocmd BufRead,BufNewFile *.tex setlocal spell spelllang=pt
endif

" Add all your plugins here
Plugin 'vim-scripts/indentpython.vim'
Plugin 'lervag/vimtex'
Plugin 'plasticboy/vim-markdown'
Plugin 'iamcco/markdown-preview.nvim'
Plugin 'godlygeek/tabular'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'lilydjwg/colorizer'
Plugin 'jalvesaq/Nvim-R'
Plugin 'junegunn/goyo.vim'
Plugin 'sillybun/vim-repl'
"Plugin 'vimwiki/vimwiki'
"Plugin 'preservim/nerdtree'
"Plugin 'vim-pandoc/vim-pandoc'
"Plugin 'vim-pandoc/vim-pandoc-syntax' 
"Plugin 'vim-syntastic/syntastic'
"Plugin 'christoomey/vim-system-copy'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" VUNDLE SECTION END
" ------------------------------------------------------------------ "

" --------------- "
" EXTERNAL CONFIG
" --------------- "

" Autoclose stuff
source ~/.vim/config/autoclose.vim
" Appearance
source ~/.vim/config/appearance.vim
" Recorded macros
source ~/.vim/config/macros.vim
" LaTeX
source ~/.vim/config/vimtex.vim
" JupyText
source ~/.vim/config/jupytext.vim
" R
source ~/.vim/config/nvimr.vim
" Python
source ~/.vim/config/python.vim
" Markdown
source ~/.vim/config/markdown.vim

" Turn on syntax highlighting.
syntax on
syntax enable

" Indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
"set textwidth=79
set expandtab
set autoindent
"set fileformat=unix

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number
set relativenumber

" Always show the status line at the bottom, 
" even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from 
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**
set wildmenu

" Unbind some useless/annoying default key bindings.
"nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support
set mouse+=a

" Remap movement and escape keys
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
inoremap <esc> <nop>
inoremap jk <esc>

" Don't break words
set wrap linebreak

" Specifying different areas of the screen where the splits should occur
set splitbelow
set splitright

" Split navigations
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

" UTF-8 support
set encoding=utf-8

" remap copy/paste commands
nnoremap <C-y> "+y
vnoremap <C-y> "+y
nnoremap <C-p> "+gP
vnoremap <C-p> "+gP

" use ç instead of ^
nnoremap ç ^
vnoremap ç ^
