# alacritty theme catfrappe
[colors.primary]
background = "0x303446"
foreground = "0xc6d0f5"
[colors.normal]
black = "0x51576d"
red = "0xe78284"
green = "0xa6d189"
yellow = "0xe5c890"
blue = "0x8caaee"
magenta = "0xf4b8e4"
cyan = "0x81c8be"
white = "0xb5bfe2"
[colors.bright]
black = "0x626880"
red = "0xe78284"
green = "0xa6d189"
yellow = "0xe5c890"
blue = "0x8caaee"
magenta = "0xf4b8e4"
cyan = "0x81c8be"
white = "0xa5adce"
